readme, installation.pdf, z

diff --git a/z b/z
--- a/z
+++ b/z
@@ -25,22 +25,23 @@ echo C O M P I L I N G
 set +e
 ./compiler
 
-if [ $? -ne 0 ]
+if [ $? -ne 0 ] #if ./compiler returns non-zero exit status
 then 	
-		ddd -silent -x ~/gdb --eval-command=quit ./compiler
+		echo 'if ddd is not installed run with gdb'
+		ddd -silent -x ~/gdb --eval-command=quit ./compiler #debugging
 		exit
 fi
 
 lex elabel.l
-#tcc -g lex.yy.c -o labeller
 gcc -g lex.yy.c -o labeller
 echo L A B E L L I N G
 echo
 ./labeller
 
-if [ $? -ne 0 ]
+if [ $? -ne 0 ] #if ./labeller returns non-zero exit status
 then 	
-		ddd -silent -x ~/gdb --eval-command=quit ./labeller
+		echo 'if ddd is not installed run with gdb'
+		ddd -silent -x ~/gdb --eval-command=quit ./labeller #debugging
 		exit
 fi
 #cd $root
